const Menu = [
  {
    id: 1,
    image: "images/noodles.jpg",
    name: "Noodles",
    category: "breakfast",
    price: "12₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },

  {
    id: 2,
    image: "images/burger.jpg",
    name: "Burger",
    category: "evening",
    price: "20₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 3,
    image: "images/corn.jpg",
    name: "corn",
    category: "breakfast",
    price: "10₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 4,
    image: "../images/rice.jpg",
    name: "Rice",
    category: "lunch",
    price: "50₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 5,
    image: "../images/pizza.jpg",
    name: "pizza",
    category: "evening",
    price: "80₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 6,
    image: "../images/non_veg.jpg",
    name: "Non-Veg Thali",
    category: "dinner",
    price: "180₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 7,
    image: "../images/sweets.jpg",
    name: "Sweets",
    category: "dinner",
    price: "60₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 8,
    image: "../images/eggrice.jpg",
    name: "Egg Rice",
    category: "lunch",
    price: "60₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
  {
    id: 9,
    image: "../images/samosa.jpg",
    name: "samaso",
    category: "evening",
    price: "10₹",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
  },
];

export default Menu;
